#!/usr/bin/env python3
"""
Douban Collection Export via Frodo API (Mobile App Backend)

Exports book/movie/music/game collections to Markdown, CSV or JSON.
No login, no cookies, no browser required.

Derived from daymade/claude-code-skills (douban-skill), MIT licensed.
The Frodo API approach, HMAC signature scheme and rate-limit values come
from that project. See README.md for full attribution.

The API key and HMAC secret are Douban's mobile app credentials, extracted
from the public APK. They are the same for all users and do not identify you.
No personal credentials are used or stored. Data is fetched only from
frodo.douban.com.

Usage:
    python3 douban-export.py --user <id>
    python3 douban-export.py --format json --type movie,book
    python3 douban-export.py --output-dir ~/notes/media
"""

import argparse
import base64
import csv
import hashlib
import hmac
import json
import os
import re
import socket
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

# --- Frodo API auth ---
# Public credentials from the Douban Android APK, shared by all app users.
API_KEY = '0dad551ec0f84ed02907ff5c42e8ec70'
HMAC_SECRET = b'bf7dddc7c9cfe6f7'
BASE_URL = 'https://frodo.douban.com'
USER_AGENT = (
    'api-client/1 com.douban.frodo/7.22.0.beta9(231) Android/23 '
    'product/Mate40 vendor/HUAWEI model/Mate40 brand/HUAWEI '
    'rom/android network/wifi platform/AndroidPad'
)

# --- Rate limiting ---
# Values inherited from upstream, tested with 1200+ items. Do not lower these.
PAGE_DELAY = 1.5
CATEGORY_DELAY = 2.0
ITEMS_PER_PAGE = 50
MAX_PAGES_SAFETY = 500

# --- Categories ---
# (api_type, api_status, chinese_label)
CATEGORIES = [
    ('book',  'done',  '读过'),
    ('book',  'doing', '在读'),
    ('book',  'mark',  '想读'),
    ('movie', 'done',  '看过'),
    ('movie', 'doing', '在看'),
    ('movie', 'mark',  '想看'),
    ('music', 'done',  '听过'),
    ('music', 'doing', '在听'),
    ('music', 'mark',  '想听'),
    ('game',  'done',  '玩过'),
    ('game',  'doing', '在玩'),
    ('game',  'mark',  '想玩'),
]

TYPES = ['book', 'movie', 'music', 'game']

# Output basename per type. English on purpose: the default output directory is
# the current directory, so these names land in other people's repos and shells.
OUTFILE = {
    'book':  'books',
    'movie': 'movies',
    'music': 'music',
    'game':  'games',
}

URL_PREFIX = {
    'book':  'https://book.douban.com/subject/',
    'movie': 'https://movie.douban.com/subject/',
    'music': 'https://music.douban.com/subject/',
    'game':  'https://www.douban.com/game/',
}

FIELDS = ['title', 'card_subtitle', 'url', 'date', 'rating', 'status', 'comment', 'tags']

CONFIG_PATH = os.path.expanduser('~/.config/douban-export/config.json')

GENERATED_NOTE = '<!-- Generated by douban-export-skill. Do not edit by hand: this file is overwritten on every run. -->'


# --- Config -----------------------------------------------------------------

def load_config():
    try:
        with open(CONFIG_PATH, encoding='utf-8') as f:
            return json.load(f)
    except (OSError, ValueError):
        return {}


def save_config(cfg):
    """Persist config outside the repo, so a committed output dir never leaks it."""
    try:
        os.makedirs(os.path.dirname(CONFIG_PATH), exist_ok=True)
        with open(CONFIG_PATH, 'w', encoding='utf-8') as f:
            json.dump(cfg, f, ensure_ascii=False, indent=2)
    except OSError as e:
        print(f'Warning: could not save config to {CONFIG_PATH}: {e}')


def resolve_user(arg_user):
    """Resolve the Douban user ID: CLI arg > env var > config file."""
    for value in (arg_user, os.environ.get('DOUBAN_USER'), load_config().get('user')):
        if value and value.strip():
            return normalize_user(value.strip())
    return None


def normalize_user(value):
    m = re.search(r'douban\.com/people/([A-Za-z0-9._-]+)', value)
    if m:
        value = m.group(1)
    if not re.match(r'^[A-Za-z0-9._-]+$', value):
        sys.exit(f'Error: invalid Douban user ID: {value}')
    return value


# --- HTTP -------------------------------------------------------------------

def compute_signature(url_path, timestamp):
    """Frodo HMAC-SHA1: signs METHOD & url_encoded_path & timestamp (path only)."""
    raw = '&'.join(['GET', urllib.parse.quote(url_path, safe=''), timestamp])
    return base64.b64encode(hmac.new(HMAC_SECRET, raw.encode(), hashlib.sha1).digest()).decode()


def fetch(path, params):
    """The single outbound request choke point.

    Every API call goes through here. If authenticated requests are ever needed,
    this is the only function that has to change.
    """
    ts = str(int(time.time()))
    signed = dict(params, apiKey=API_KEY, _ts=ts, _sig=compute_signature(path, ts), os_rom='android')
    url = f'{BASE_URL}{path}?{urllib.parse.urlencode(signed)}'
    req = urllib.request.Request(url, headers={'User-Agent': USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.loads(resp.read().decode('utf-8')), resp.status
    except urllib.error.HTTPError as e:
        return {'error': e.read().decode('utf-8', errors='replace')[:200], 'code': e.code}, e.code
    except urllib.error.URLError as e:
        return {'error': f'Network error: {e.reason}'}, 0
    except socket.timeout:
        return {'error': 'Request timed out'}, 0
    except json.JSONDecodeError as e:
        return {'error': f'Invalid JSON response: {e}'}, 0


def preflight(user_id):
    """Fail fast on a bad user ID instead of grinding through 12 categories."""
    data, code = fetch(f'/api/v2/user/{user_id}/interests',
                       {'type': 'book', 'status': 'done', 'start': 0, 'count': 1})
    if code == 0:
        print('Warning: could not verify user ID (network issue). Proceeding anyway.')
        return True
    if code != 200:
        print(f'Error: API returned HTTP {code} for user "{user_id}".')
        print('  Check the ID from your profile URL: douban.com/people/<ID>/')
        return False
    return True


def fetch_all(user_id, type_name, status):
    """Paginate one type+status combination. Trusts `total`, not page size."""
    path = f'/api/v2/user/{user_id}/interests'
    items, start, total, retries, pages = [], 0, None, 0, 0

    while pages < MAX_PAGES_SAFETY:
        pages += 1
        data, code = fetch(path, {'type': type_name, 'status': status,
                                  'start': start, 'count': ITEMS_PER_PAGE})
        if code != 200:
            retries += 1
            if retries > 3:
                print(f'  Error: HTTP {code} after 3 retries, giving up on this category.')
                print('  See references/troubleshooting.md')
                break
            delay = 5 * (2 ** (retries - 1))
            print(f'  HTTP {code}, retry {retries}/3 in {delay}s...')
            time.sleep(delay)
            continue
        retries = 0

        if total is None:
            total = data.get('total', 0)
            if total == 0:
                return []
            print(f'  Total: {total}')

        batch = data.get('interests', [])
        if not batch:
            break
        items.extend(batch)
        print(f'  Fetched {len(items)}/{total}')
        if len(items) >= total:
            break
        start += len(batch)
        time.sleep(PAGE_DELAY)

    return items


# --- Mapping ----------------------------------------------------------------

def to_stars(interest):
    r = interest.get('rating')
    if not isinstance(r, dict):
        return ''
    val = r.get('value', 0)
    if not val:
        return ''
    stars = round(val) if r.get('max', 5) <= 5 else round(val / 2)
    return '★' * max(0, min(5, stars))


def to_row(interest, type_name, status_cn):
    """Flatten one API interest into an output row.

    `card_subtitle` is the one metadata field all four types share: Douban has
    already joined director/genre/year (movies) or author/press (books) into a
    single line, so we don't need a per-type field mapping.
    """
    subject = interest.get('subject', {})
    sid = subject.get('id', '')
    url = f'{URL_PREFIX.get(type_name, "")}{sid}/' if sid else subject.get('url', '')
    date = (interest.get('create_time') or '')[:10]
    if not re.match(r'^\d{4}-\d{2}-\d{2}$', date):
        date = ''
    tags = interest.get('tags') or []
    return {
        'title': subject.get('title', ''),
        'card_subtitle': subject.get('card_subtitle', ''),
        'url': url,
        'date': date,
        'rating': to_stars(interest),
        'status': status_cn,
        'comment': interest.get('comment', '') or '',
        'tags': ' '.join(tags) if isinstance(tags, list) else str(tags),
    }


# --- Writers ----------------------------------------------------------------

def md_cell(value):
    """Escape a value for a Markdown table cell."""
    return str(value).replace('|', '\\|').replace('\n', '<br>').strip()


def write_md(path, rows, heading):
    with open(path, 'w', encoding='utf-8') as f:
        f.write(f'# {heading}\n\n{GENERATED_NOTE}\n\n')
        f.write(f'共 {len(rows)} 条，导出时间 {time.strftime("%Y-%m-%d %H:%M")}\n\n')
        f.write('| ' + ' | '.join(FIELDS) + ' |\n')
        f.write('|' + '---|' * len(FIELDS) + '\n')
        for r in rows:
            f.write('| ' + ' | '.join(md_cell(r[k]) for k in FIELDS) + ' |\n')


def write_csv(path, rows, _heading):
    with open(path, 'w', newline='', encoding='utf-8-sig') as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        w.writerows(rows)


def write_json(path, rows, _heading):
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(rows, f, ensure_ascii=False, indent=2)


WRITERS = {'md': write_md, 'csv': write_csv, 'json': write_json}

HEADINGS = {'book': '豆瓣读书', 'movie': '豆瓣影视', 'music': '豆瓣音乐', 'game': '豆瓣游戏'}


# --- Main -------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(
        prog='douban-export',
        description='Export Douban book/movie/music/game collections.')
    p.add_argument('--user', '-u', help='Douban user ID or profile URL '
                                        '(falls back to $DOUBAN_USER, then ~/.config/douban-export/config.json)')
    p.add_argument('--output-dir', '-o', default='.',
                   help='Where to write the files (default: current directory)')
    p.add_argument('--format', '-f', default='md', choices=sorted(WRITERS),
                   help='Output format (default: md)')
    p.add_argument('--type', '-t', default=','.join(TYPES),
                   help='Comma-separated subset of: book,movie,music,game (default: all)')
    return p.parse_args()


def main():
    args = parse_args()

    user_id = resolve_user(args.user)
    if not user_id:
        sys.exit('Error: no Douban user ID. Pass --user <id>, set $DOUBAN_USER, '
                 'or run once with --user to save it to ~/.config/douban-export/config.json')

    wanted = [t.strip() for t in args.type.split(',') if t.strip()]
    unknown = [t for t in wanted if t not in TYPES]
    if unknown:
        sys.exit(f'Error: unknown --type value(s): {", ".join(unknown)}. Valid: {", ".join(TYPES)}')

    out_dir = os.path.abspath(os.path.expanduser(args.output_dir))
    os.makedirs(out_dir, exist_ok=True)

    print(f'Douban export | user: {user_id} | format: {args.format} | types: {",".join(wanted)}')
    print(f'Output: {out_dir}\n')

    if not preflight(user_id):
        sys.exit(1)

    by_type = {t: [] for t in wanted}
    for type_name, status, status_cn in CATEGORIES:
        if type_name not in by_type:
            continue
        print(f'=== {status_cn} ({type_name}) ===')
        items = fetch_all(user_id, type_name, status)
        by_type[type_name].extend(to_row(i, type_name, status_cn) for i in items)
        print(f'  Collected: {len(items)}\n' if items else '  (empty)\n')
        time.sleep(CATEGORY_DELAY)

    print('--- Writing files ---')
    written = 0
    for type_name in wanted:
        rows = by_type[type_name]
        if not rows:
            print(f'  {OUTFILE[type_name]}.{args.format}: skipped (no items)')
            continue
        path = os.path.join(out_dir, f'{OUTFILE[type_name]}.{args.format}')
        WRITERS[args.format](path, rows, HEADINGS[type_name])
        print(f'  {os.path.basename(path)}: {len(rows)} rows')
        written += len(rows)

    # Remember the ID only after a successful run.
    cfg = load_config()
    if cfg.get('user') != user_id:
        cfg['user'] = user_id
        save_config(cfg)
        print(f'\nSaved user ID to {CONFIG_PATH} (next run needs no --user).')

    print(f'\nDone. {written} items exported to {out_dir}')


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('\n\nInterrupted.')
        sys.exit(130)
